name: Trigger Website Changelog

on:
  release:
    types: [published, edited]

jobs:
  notify-website-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to Website Repo
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.WEBSITE_REPO_PAT }}
          repository: niklasr22/brightintosh-website
          event-type: app_release
          client-payload: '{"version": "${{ github.event.release.tag_name }}", "app_repo": "${{ github.repository }}"}'